common/models/ImgSlider.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "img_slider".
 *
 * @property int $id
 * @property string $img_nombre
 * @property int $posicion
 * @property int $numero_slider
 * @property string $url
 */
class ImgSlider extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'img_slider';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['posicion', 'numero_slider'], 'required'],
            [['posicion', 'numero_slider'], 'integer'],
            [['img_nombre', 'url'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'img_nombre' => 'Img Nombre',
            'posicion' => 'Posicion',
            'numero_slider' => 'Numero Slider',
            'url' => 'Url',
        ];
    }

    public static function getAll_ImgSlider($numero_slider) {
        return ImgSlider::find()->where(['numero_slider' => $numero_slider])->orderBy(['posicion'=>SORT_ASC])->all(); // Equivalente a SELECT * FROM BASE_DE_DATOS.img_banner WHERE numero_slider = 1; // SORT_ASC/SORT_DESC
    }
}

backend/controllers/ImgSliderController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\ImgSlider;
use common\models\Slider;
use common\models\ImgSliderSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * ImgSliderController implements the CRUD actions for ImgSlider model.
 */
class ImgSliderController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all ImgSlider models.
     * @return mixed
     */
    public function actionIndex($id_slider, $numero_slider)
    {
        $searchModel = new ImgSliderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $dataProvider->query->andWhere(['numero_slider' => $numero_slider]);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'id_slider' => $id_slider,
            'numero_slider' => $numero_slider,
        ]);
    }

    /**
     * Displays a single ImgSlider model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new ImgSlider model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($id_slider, $numero_slider)
    {
        $model = new ImgSlider();

        /*if ($model->load(Yii::$app->request->post()) && $model->save()) {
            //return $this->redirect(['view', 'id' => $model->id]);
            return $this->redirect(['index', 'numero_slider' => $numero_slider]);
        }*/

        if ($model->load(Yii::$app->request->post())) {

            // Imagen
            $img_nombre = UploadedFile::getInstance($model, 'img_nombre');
            if (isset($img_nombre)) {
                $tmp = explode('.', $img_nombre->name);
                $ext = end($tmp);
                $model->img_nombre = Yii::$app->security->generateRandomString().".{$ext}";

                Yii::$app->params['uploadPath'] = Yii::$app->basePath . '/../archivos/';
                $path = Yii::$app->params['uploadPath'] . $model->img_nombre;
                $img_nombre->saveAs($path);
            }

            if ($model->save()) {
                Yii::$app->session->setFlash('success', 'Datos guardados correctamente.');
                //return $this->redirect(['update', 'id' => $model->id]);
                return $this->redirect(['index', 'id_slider' => $id_slider, 'numero_slider' => $numero_slider]);
            }

        }

        return $this->render('create', [
            'model' => $model,
            'id_slider' => $id_slider,
            'numero_slider' => $numero_slider,
        ]);
    }

    /**
     * Updates an existing ImgSlider model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model_original = $this->findModel($id);
        $model = $this->findModel($id);

        $numero_slider = $model->numero_slider;

        $id_slider = Slider::find()->where(['numero_slider' => $numero_slider])->one();
        $id_slider = $id_slider->id;

        if ($model->load(Yii::$app->request->post())) {

            // Imagen
            $img_nombre = UploadedFile::getInstance($model, 'img_nombre');
            if (isset($img_nombre)) {
                $tmp = explode('.', $img_nombre->name);
                $ext = end($tmp);
                $model->img_nombre = Yii::$app->security->generateRandomString().".{$ext}";

                Yii::$app->params['uploadPath'] = Yii::$app->basePath . '/../archivos/';
                $path = Yii::$app->params['uploadPath'] . $model->img_nombre;
                $img_nombre->saveAs($path);
            } else {
                $model->img_nombre = $model_original->img_nombre;
            }

            if ($model->save()) {
                Yii::$app->session->setFlash('success', 'Datos guardados correctamente.');
                //return $this->redirect(['update', 'id' => $model->id]);
                return $this->redirect(['index', 'id' => $model->id, 'id_slider' => $id_slider, 'numero_slider' => $numero_slider]);
            }

        }

        return $this->render('update', [
            'model' => $model,
            'id_slider' => $id_slider,
            'numero_slider' => $numero_slider,
        ]);
    }

    /**
     * Deletes an existing ImgSlider model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        //$this->findModel($id)->delete();

        $model = $this->findModel($id);
        $numero_slider = $model->numero_slider;

        $id_slider = Slider::find()->where(['numero_slider' => $numero_slider])->one();
        $id_slider = $id_slider->id;

        $model->delete();

        return $this->redirect(['index', 'id_slider' => $id_slider, 'numero_slider' => $numero_slider]);
    }

    /**
     * Finds the ImgSlider model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return ImgSlider the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ImgSlider::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/controllers/SliderController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Slider;
use common\models\SliderSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * SliderController implements the CRUD actions for Slider model.
 */
class SliderController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Slider models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SliderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Slider model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Slider model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Slider();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Slider creado correctamente.');
            //return $this->redirect(['view', 'id' => $model->id]);
            return $this->redirect(['index']);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Slider model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            //return $this->redirect(['view', 'id' => $model->id]);
            Yii::$app->session->setFlash('success', 'Datos guardados correctamente.');
            return $this->redirect(['index', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Slider model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        Yii::$app->session->setFlash('success', 'Slider eliminado correctamente.');
        return $this->redirect(['index']);
    }

    /**
     * Finds the Slider model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Slider the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Slider::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/img-slider/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\file\FileInput;

/* @var $this yii\web\View */
/* @var $model common\models\ImgSlider */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="img-slider-form">

    <?php
        if ($model->img_nombre == null) {
            $img_nombre = null;
        } else {
            $img_nombre = '../../archivos/'.$model->img_nombre;
        }
    ?>

    <?php $form = ActiveForm::begin(['options'=>['enctype'=>'multipart/form-data']]); ?>

    <?php
        if (isset($model->numero_slider)) {
            $numero_slider_actual = $model->numero_slider;
        } else {
            $numero_slider_actual = $numero_slider;
        }
    ?>

    <div class="row">
        <div class="col-lg-3">
            <?= $form->field($model, 'numero_slider')->textInput(['maxlength' => true, 'readonly' => true, 'value' => $numero_slider_actual])->label('N° de slider') ?>
            <!--<? //= $form->field($model, 'numero_slider')->hiddenInput(['maxlength' => true, 'readonly' => true, 'value' => $numero_slider])->label(false); ?>-->
        </div>

        <div class="col-lg-3">
            <?= $form->field($model, 'posicion')->textInput()->label('Posición') ?>
        </div>
    </div>

    <!--<? //= $form->field($model, 'img_nombre')->textInput(['maxlength' => true])->label('Imagen') ?>-->
    <div class="row">
        <!-- Imagen -->
        <div class="col-lg-4">
            <?= $form->field($model, 'img_nombre')->widget(FileInput::classname(), [
                'options' => ['accept' => 'image/*'], 
                'pluginOptions' => [
                    'showClose' => false,
                    'showRemove' => false,
                    'showUpload' => false,
                    'showCaption' => false,

                    'initialPreview' => [
                        $img_nombre,
                    ],
                'initialPreviewAsData' => true,
                ],
            ])->label('Imagen'); ?>
        </div>
    </div>

    <?= $form->field($model, 'url')->textInput(['maxlength' => true])->label('URL') ?>

    <hr>

    <div class="form-group">
        <p align="right"><?= Html::submitButton('Guardar', ['class' => 'btn btn-default']) ?></p>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/img-slider/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\ImgSliderSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="img-slider-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'img_nombre') ?>

    <?= $form->field($model, 'posicion') ?>

    <?= $form->field($model, 'numero_slider') ?>

    <?= $form->field($model, 'url') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/img-slider/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\ImgSlider */

$this->title = 'Agregar imagen a slider '.$numero_slider;
//$this->params['breadcrumbs'][] = ['label' => 'Img Sliders', 'url' => ['index']];
//$this->params['breadcrumbs'][] = $this->title;

$this->params['breadcrumbs'][] = ['label' => 'Sliders', 'url' => ['slider/index']];
$this->params['breadcrumbs'][] = ['label' => 'Configuración (Slider '.$numero_slider.')', 'url' => ['slider/update', 'id' => $id_slider]];
$this->params['breadcrumbs'][] = ['label' => 'Agregar imagen a slider '.$numero_slider, 'url' => ['img-slider/index', 'id_slider' => $id_slider, 'numero_slider' => $numero_slider]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="img-slider-create">

    <h3><?= Html::encode($this->title) ?></h3>
    <hr>

    <?= $this->render('_form', [
        'model' => $model,
        'numero_slider' => $numero_slider,
    ]) ?>

</div>

backend/views/img-slider/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\ImgSliderSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Imágenes de slider '.$numero_slider;
$this->params['breadcrumbs'][] = ['label' => 'Sliders', 'url' => ['slider/index']];
$this->params['breadcrumbs'][] = ['label' => 'Configuración (Slider '.$numero_slider.')', 'url' => ['slider/update', 'id' => $id_slider]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="img-slider-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <!--<p align="right"><? //= Html::a('Cargar imagen a slider '.$numero_slider, ['create'], ['class' => 'btn btn-default']) ?></p>-->
        <p align="right"><?= Html::a('Agregar imagen a slider '.$numero_slider, ['create', 'id_slider' => $id_slider, 'numero_slider' => $numero_slider], ['class'=>'btn btn-default']) ?></p>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            //['class' => 'yii\grid\SerialColumn'],

            //'id',
            
            //'img_nombre',
            [
                'attribute' => 'img_nombre',
                'format' => 'html',
                'value' => function ($data) {
                    return Html::img(Yii::getAlias('@web').'/../../archivos/'. $data['img_nombre'], ['width' => '70px']);
                },
            ],

            'posicion',
            //'numero_slider',
            'url:url',

            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{update} {delete}',
            ],
        ],
    ]); ?>


</div>

backend/views/img-slider/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\ImgSlider */

$this->title = 'Actualizar imagen';
$this->params['breadcrumbs'][] = ['label' => 'Sliders', 'url' => ['slider/index']];
$this->params['breadcrumbs'][] = ['label' => 'Configuración (Slider '.$numero_slider.')', 'url' => ['slider/update', 'id' => $id_slider]];
$this->params['breadcrumbs'][] = ['label' => 'Agregar imagen a slider '.$numero_slider, 'url' => ['img-slider/index', 'id_slider' => $id_slider, 'numero_slider' => $numero_slider]];
$this->params['breadcrumbs'][] = $this->title;
//$this->params['breadcrumbs'][] = ['label' => 'Img Sliders', 'url' => ['index']];
//$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
//$this->params['breadcrumbs'][] = 'Update';
?>
<div class="img-slider-update">

    <h3><?= Html::encode($this->title) ?></h3>
    <hr>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/img-slider/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\ImgSlider */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Img Sliders', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="img-slider-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'img_nombre',
            'posicion',
            'numero_slider',
            'url:url',
        ],
    ]) ?>

</div>